baseURL = "https://hophamlam.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "mySocialSensei"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]

  name = "hophamlam"
  headline = "👋🐵⌨️👪🍚"
  image = "DSC_8770.JPG"  # path relative to static directory

  links = [
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/hophamlam" },
    { telegram = "https://t.me/hophamlam" },
    # { gitlab = "https://gitlab.com/hophamlam" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    { steam = "https://steamcommunity.com/profiles/76561198053167250" },
    # { discord = "https://discord.gg/V8rM4zb6" },

    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/hophamlam" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
    # { email = "mailto:hophamlam@yahoo.com" },
    { soundcloud = "https://soundcloud.com/hophamlam" },

    { link = { href = "https://blog.hophamlam.com/", text = "Hashnode" } },



  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
